<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 -  Introducción a Numpy



## Objetivos de la clase

* Aprender conceptos básicos de la librería numpy.


## Contenidos

* [Numpy](#c1)

<a id='c1'></a>

## I.- Numpy 

<img src="images/numpy.jpeg" width="360" height="240" align="center"/>

**NumPy** es el paquete fundamental para la computación científica con Python. Contiene entre otras cosas:

 * un poderoso objeto de matriz N-dimensional
 * funciones sofisticadas (de transmisión)
 * herramientas para integrar código C / C ++ y Fortran
 * Álgebra lineal útil, transformada de Fourier y capacidades de números aleatorios

Además de sus obvios usos científicos, NumPy también se puede utilizar como un eficiente contenedor multidimensional de datos genéricos. Se pueden definir tipos de datos arbitrarios. Esto permite que  NumPy se integre sin problemas y rápidamente con una amplia variedad de bases de datos.

NumPy tiene licencia bajo la licencia BSD, lo que permite su reutilización con pocas restricciones.
 
### ¿ Por qué usar Numpy ?

Las razones por las que debería usar NumPy en lugar de cualquier otro objeto `_iterable` en Python son:

* NumPy proporciona una estructura de ndarray para almacenar datos numéricos de manera contigua.
* También implementa operaciones matemáticas rápidas en ndarrays, que explotan esta contigüidad.
* Brevedad de la sintaxis para las operaciones de matriz.

Un lenguaje como C o Java requeriría que escribamos un bucle para una operación matricial tan simple como C = A + B. 

###  1.- Operaciones básicas de NumPy
Las razones por las que debería usar NumPy en lugar de cualquier otro objeto `_iterable` en Python son:

* NumPy proporciona una estructura de ndarray para almacenar datos numéricos de manera contigua.
* También implementa operaciones matemáticas rápidas en ndarrays, que explotan esta contigüidad.
* Brevedad de la sintaxis para las operaciones de matriz.

Un lenguaje como C o Java requeriría que escribamos un bucle para una operación matricial tan simple como C = A + B. 

In [7]:
# importar libreria: numpy
import numpy as np
import time
import sys

In [8]:
# Arreglo de ceros: np.zeros(shape)
print("Zeros:")
print( np.zeros((3,3)) )

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Arreglos de uno: np.ones(shape)
print("\nOnes:")
print( np.ones((3,3)) )


Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Arreglo vacio: np.empty(shape)
print("\nEmpty:")
print( np.empty([2, 2]) )


Empty:
[[4.67843613e-310 6.90454990e-310]
 [0.00000000e+000 0.00000000e+000]]


In [11]:
# Rango de valores: np.range(start, stop, step)
print("\nRange:")
print( np.arange(0., 10., 1.) )


Range:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [12]:
# Grilla de valores: np.linspace(start, end, n_values)
print("\nRegular grid:")
print( np.linspace(0., 1., 9) )


Regular grid:
[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [13]:
# fijar semilla
np.random.seed(42)

# Sequencia aleatoria: np.random
print("\nRandom sequences:")
print( np.random.uniform(10, size=6) )


Random sequences:
[6.62913893 1.44357124 3.41205452 4.61207364 8.59583224 8.59604932]


In [14]:
# Construccion de arreglos: np.array( python_iterable )
print("\nArray constructor")
print( np.array([2, 3, 5, 10, -1]) )


Array constructor
[ 2  3  5 10 -1]


### 2.- Operaciones matemáticas básicas de matrices
La mayoría de las operaciones realizadas en NumPy se manejan por elementos, es decir, calcular C = A + B se traducirá en $ C [i, j] = A [i, j] + B [i, j] $. (La excepción es la transmisión y se explicará pronto).

A continuación hay una lista con las operaciones matemáticas más comunes. 

In [15]:
# fijar semilla
np.random.seed(42)

# crear dos arreglos
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print(f"Matrix A: \n {A} \n")
print(f"Matrix B: \n {B}")

Matrix A: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Matrix B: 
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [16]:
# suma
print("Sum:")
print( A+B )

Sum:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [17]:
# resta
print("\nSubtraction")
print( A-B )


Subtraction
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [18]:
# producto uno a uno
print("\nProduct")
print( A*B )


Product
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [19]:
# producto matricial
print("\nMatricial Product")
print( np.dot(A,B) )


Matricial Product
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [20]:
# potencia
print("\n Power")
print( A**2 )


 Power
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [21]:
# funciones trigonometricas
print("\n np.exp()")
print( np.exp(A) )
print("\n np.sin()")
print( np.sin(A) )
print("\n np.cos()")
print( np.cos(A))
print("\n np.tan()")
print( np.tan(A) )


 np.exp()
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

 np.sin()
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]

 np.cos()
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

 np.tan()
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


### 3.- Álgebra Lineal

En esta sección se presentan algunas propiedades comunmente ocupadas en álgebra lineal de matrices.

In [22]:
# crear un arreglo

A = np.array([[1,2],
              [3,4]])

In [23]:
# transpuesta
print("Transpose: ")
print( A.T )

Transpose: 
[[1 3]
 [2 4]]


In [24]:
# determinante
print("determinant")
print( round(np.linalg.det(A) ,2))

determinant
-2.0


In [19]:
# Inversa
print("Inverse")
print( np.linalg.inv(A) )

Inverse
[[-2.   1. ]
 [ 1.5 -0.5]]


In [20]:
# traza
print("Trace")
print( np.trace(A))

Trace
5


In [21]:
# sistemas lineales: Ax = b
y = np.array([[5.], [7.]])

print("linear system: Ax=y")
print("\nx = ")
print( np.linalg.solve(A, y) )

linear system: Ax=y

x = 
[[-3.]
 [ 4.]]


In [22]:
# Valores y vectores propios
eigenvalues,eigenvectors = np.linalg.eig(A) 

print("eigenvalues")
print( eigenvalues )
print("\neigenvectors")
print( eigenvectors )

eigenvalues
[-0.37228132  5.37228132]

eigenvectors
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [23]:
# descomposicion QR
Q,R = np.linalg.qr(A)

print("QR decomposition:")
print("\nQ")
print( Q )
print("\nR")
print( R )

QR decomposition:

Q
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]

R
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


### 4.- Manipulación de datos

En esta sección se presentan como obtener filas y columnas de un array con numpy

In [24]:
matriz_34 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matriz_34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
# first row
print("first row:",matriz_34[0])
print("first col:",matriz_34[:,0],'\n')
print("first and second rows: \n", matriz_34[:2],'\n')
print("first and second cols: \n", matriz_34[:,:2],'\n')

first row: [1 2 3 4]
first col: [1 5 9] 

first and second rows: 
 [[1 2 3 4]
 [5 6 7 8]] 

first and second cols: 
 [[ 1  2]
 [ 5  6]
 [ 9 10]] 



### 5.- Broadcasting

Unas de las ventajas de numpy es que podemos hacer  **broadcasting**, es to significa que numpy permite realizar operaciones binarias con arreglos de distintos tamaños.


<img src="https://www.astroml.org/_images/fig_broadcast_visual_1.png" width="360" height="240" align="center"/>



In [36]:
# example 01
a = np.arange(3)+ 5
print(f"np.arange(3)+ 5:\n{a}" )

np.arange(3)+ 5:
[5 6 7]


In [35]:
# example 02
b = np.ones((3,3))+np.arange(3)
print(f"np.ones((3,3))+np.arange(3):\n{b}" )

np.ones((3,3))+np.arange(3):
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [39]:
# example 03
c = np.arange(3).reshape((3,1)) +  np.arange(3)
print(f"np.arange(3).reshape((3,1)) +  np.arange(3):\n{c }" )

np.arange(3).reshape((3,1)) +  np.arange(3):
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### 6.-Python Lists vs. Numpy Arrays


La librería principal de Python son las listas. Una lista es el equivalente a Python de una matriz, pero es redimensionable y puede contener elementos de diferentes tipos.

Una pregunta común para principiantes es cuál es la verdadera diferencia aquí. La respuesta es el **rendimiento**. Las estructuras de datos de Numpy funcionan mejor en:

* **Tamaño**: las estructuras de datos de Numpy ocupan menos espacio
* **Rendimiento**: necesitan velocidad y son más rápidos que las listas
* **Funcionalidad**: SciPy y NumPy tienen funciones optimizadas, como las operaciones de álgebra lineal integradas.

### Memoria

Los principales beneficios del uso de matrices NumPy deberían ser un menor consumo de memoria y un mejor comportamiento en tiempo de ejecución.

Para las listas de Python: podemos concluir de esto que para cada elemento nuevo, necesitamos otros ocho bytes para la referencia al nuevo objeto. El nuevo objeto entero en sí consume 28 bytes. El tamaño de una lista **lst** sin el tamaño de los elementos se puede calcular con:

                        64 + 8 * len (lst) + + len (lst) * 28
                        
                        
<img src="images/list_structure.png" width="360" height="240" align="center"/>


NumPy ocupa menos espacio. Esto significa que una matriz entera arbitraria de longitud **n** en necesidades numpy se calcula por: 

                        96 + n * 8 bytes
                        

<img src="images/array_structure.png" width="360" height="240" align="center"/>


Para convensernos de esto, ejecutemos un ejemplo:

In [26]:
# example

# class: array
class Array:
    """
    Clase array que da como rsultado el tiempo y espacio en 
    memoria de los objetos list y numpy array
    """
    def __init__(self, size_of_vec):
        self.size_of_vec = size_of_vec

    def pure_python_version(self):
        """
        Tiempo y espacio en memoria para objeto list
        """
        t1 = time.time()
        X = range(self.size_of_vec)
        Y = range(self.size_of_vec)
        Z = [X[i] + Y[i] for i in range(len(X)) ]
        return (time.time() - t1,sys.getsizeof(Z) )
        
    def numpy_version(self):
        """
        Tiempo y espacio en memoria para objeto numpy array
        """
        t1 = time.time()
        X = np.arange(self.size_of_vec)
        Y = np.arange(self.size_of_vec)
        Z = X + Y
        return (time.time() - t1,sys.getsizeof(Z) )

In [27]:
# parameters
size_of_vec = 1000000
class_array = Array(size_of_vec)

t1, size1 = class_array.pure_python_version()
t2, size2 = class_array.numpy_version()

In [28]:
# results
print(f"python list -- time: {round(t1,8)} seg, size: {size1} bytes")
print(f"numpy array -- time: {round(t2,8)} seg, size: {size2} bytes")

python list -- time: 0.2977705 seg, size: 8697464 bytes
numpy array -- time: 0.00681186 seg, size: 8000096 bytes


## Referencia

1. [Quickstart tutorial-numpy](https://docs.scipy.org/doc/numpy/user/quickstart.html)
2. [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html)